### ISSUE TITLE
Prepare container-based deployment process

### ISSUE THREAD

**Issue by addianto** [pbp-fasilkom-ui/django-pbp-template#5]
# Description

Since the demise (😅) of Heroku's free tier, the deployment process needs to be revamped so the app can be built and deployed on another platform. Several PaaS that initially fit with our main constraint, i.e. without credit card verification, turned out asking for credit card information (Fly.io) at the end of November 2022 or requiring extra verification layer (Railway) based on the age of GitHub account.

Looking at the convention defined by most "free" PaaS, they support deployment process by using container. The source code of the app can be built into a container image and run on the platform. Heroku actually does support this workflow, along with aforementioned PaaS such as Fly.io and Railway. The faculty _may_ also develop a custom PaaS solution (imagine having "Heroku KW" running on `*.cs.ui.ac.id` subdomain) that following similar workflow. 

I think the template need to include a container-based deployment process that can be used for course participants in the future so they can deploy their app more conveniently to a PaaS service that might be available to them. 

## Tasks

-  [ ] Ensure the template project follows [12-Factors App Methodology](https://12factor.net/)
-  [ ] Create a `Dockerfile` that install the required dependencies (system-level and app), build, and run the project template
-  [ ] Prepare a sample guide and configuration for deploying the project template to a PaaS (e.g. Fly.io, Railway) that using container-based process
